In [12]:
import torch

In [13]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [14]:
my_tensor=torch.tensor([[1,2,3],[4,5,6],[8,9,10]], dtype=torch.float32, device=device, requires_grad=True)
print(my_tensor)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.]], requires_grad=True)


In [16]:
print(my_tensor.device)
print(my_tensor.shape)

cpu
torch.Size([3, 3])


In [17]:
x=torch.empty(size=(3,3))
print(x) 

tensor([[-3.4635e+19,  3.0830e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.4460e-44],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])


In [18]:
  x=torch.zeros(size=(3,3))
  print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [20]:
x=torch.rand((3,3))
print(x)

tensor([[0.4355, 0.3133, 0.1818],
        [0.8556, 0.7539, 0.5352],
        [0.6846, 0.8841, 0.9556]])


In [22]:
x=torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [24]:
x=torch.eye(3,3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [33]:
x=torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [31]:
x=torch.linspace(start=0.1, end=1, steps=4)
print(x)

tensor([0.1000, 0.4000, 0.7000, 1.0000])


In [36]:
x=torch.empty((3,3)).normal_(mean=0, std=1)
print(x)

tensor([[ 0.7287, -0.5879,  1.0970],
        [ 2.7379, -1.6626,  0.8312],
        [-0.4270,  0.4605, -0.6698]])


In [38]:
x=torch.empty((1,5)).uniform_(0,1)
print(x)

tensor([[0.9819, 0.7839, 0.5423, 0.6169, 0.1507]])


In [39]:
x=torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


How to initialize and convert tensors to other types

In [41]:
tensor=torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


In [46]:
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [47]:
import numpy as np

In [52]:
np_array=np.zeros((5,5))
print(np_array)
tensor=torch.from_numpy(np_array)
print(tensor)
np_array=tensor.numpy()
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Different Operations on Tensor

In [53]:
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

In [56]:
z1=torch.empty(3)
torch.add(x,y, out=z1)
print(z1)

tensor([10., 10., 10.])


In [57]:
z2=torch.add(x,y)
print(z2)

tensor([10, 10, 10])


In [58]:
z=x+y
print(x)

tensor([1, 2, 3])


In [60]:
z=x-y
print(z)

tensor([-8, -6, -4])


In [61]:
z=x/y
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [62]:
z=torch.true_divide(x,y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [63]:
t=torch.zeros(3)
print(t)

tensor([0., 0., 0.])


In [64]:
t.add_(x)

tensor([1., 2., 3.])

In [66]:
z=x.pow(2)
print(z)

tensor([1, 4, 9])


In [68]:
z=x>0
print(z)

tensor([True, True, True])


In [70]:
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2)
print(x3)

tensor([[0.7145, 1.2519, 0.6436],
        [0.9516, 1.3488, 0.6800]])


In [72]:
x3=x1.mm(x2)
print(x3)

tensor([[0.7145, 1.2519, 0.6436],
        [0.9516, 1.3488, 0.6800]])


In [75]:
matrix=torch.rand((5,5))
print(matrix.matrix_power(3))

tensor([[6.6894, 7.6726, 7.1761, 7.3764, 4.5685],
        [5.1907, 5.6094, 5.5555, 5.8746, 3.5769],
        [5.9135, 6.7386, 6.3355, 6.5210, 4.0430],
        [4.7281, 5.4158, 4.9708, 4.9960, 3.4470],
        [4.0459, 5.2659, 4.5195, 5.0648, 3.0483]])


In [76]:
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
print(torch.dot(x,y))

tensor(46)


In [82]:
batch=32
n=10
m=20
p=30

t1=torch.rand((batch, n, m))
t2=torch.rand((batch, m ,p))

out_bmm= torch.bmm(t1,t2)

In [83]:
x1=torch.rand((5,5))
x2=torch.rand((1,5))

z=x1-x2
print(z)
z=x1**x2
print(z)

tensor([[ 0.0574, -0.0120,  0.1886,  0.6045, -0.1636],
        [ 0.6206,  0.1582,  0.4227, -0.2571, -0.3830],
        [ 0.1071,  0.6343, -0.3181, -0.2631, -0.1874],
        [ 0.7550,  0.5453,  0.4912,  0.0028,  0.3009],
        [ 0.1740, -0.0724,  0.4746,  0.5984, -0.0705]])
tensor([[0.8359, 0.6953, 0.8070, 0.9922, 0.6044],
        [0.9686, 0.7967, 0.9199, 0.4485, 0.3941],
        [0.8587, 0.9718, 0.3475, 0.4398, 0.5842],
        [0.9847, 0.9455, 0.9490, 0.6942, 0.9334],
        [0.8824, 0.6467, 0.9421, 0.9899, 0.6791]])


In [ ]:
x=torch.tensor([1,2,3])

In [87]:
sum_x=torch.sum(x, dim=0)
values,indices=torch.max(x, dim=0)
z=torch.argmax(x, dim=0)
z=torch.argmin(x, dim=0)
print(z)
print(sum_x)

tensor(0)
tensor(6)


In [88]:
y=torch.tensor([9,8,7])

In [90]:
z=torch.eq(x,y)
print(z)

tensor([False, False, False])


In [93]:
x=torch.rand((3,5))
rows=torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x)
print(x[rows,cols])
print(x[rows,cols].shape)

tensor([[0.5737, 0.7260, 0.4169, 0.0509, 0.9345],
        [0.9939, 0.6658, 0.0477, 0.9780, 0.4401],
        [0.8265, 0.2635, 0.5332, 0.4618, 0.5915]])
tensor([0.4401, 0.5737])
torch.Size([2])


In [95]:
x=torch.arange(10)
print(x[(x<2) | (x>8)])
print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [102]:
print(torch.where(x>5, x, x*2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [105]:
x=torch.arange(9)
x_3x3=x.view(3,3)
print(x_3x3.shape)

torch.Size([3, 3])


In [106]:
y=x_3x3.t()
print(x_3x3,y)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [108]:
 y=y.contiguous().view(9)
 print(y)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [113]:
z=torch.cat((x,y), dim=0)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 3, 6, 1, 4, 7, 2, 5, 8])


In [115]:
z=torch.rand(2,5)
z=z.view(-1)
print(z)

tensor([0.9716, 0.2435, 0.1897, 0.5014, 0.9256, 0.4291, 0.2512, 0.5867, 0.4424,
        0.5386])


In [120]:
 x=torch.arange(10)
 print(x)
 x=x.unsqueeze(0)
 print(x)
 print(x.shape)
 x=torch.arange(10)
 print(x)
 x=x.unsqueeze(1)
 print(x)
 print(x.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])
